version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      #- MYSQL_DATABASE=demo_park
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
  mysql-db-data:
  # db:
  #   driver: local
