spring:
  application:
    name:demo-jpa-integrationtest
  datasource:
    url: jdbc:mysql://localhost:3306/integrationtestdb?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop
    hibernate:
      jdbc: time_zone = TimeZone
      show-sql: true

  jackson:
    default-property-inclusion: NON_NULL

server:
  error:
    include-message: always